from django.http import JsonResponse
from rest_framework import viewsets
from django.shortcuts import get_object_or_404
from rest_framework.renderers import JSONRenderer

from rest_framework.decorators import action

from django.contrib.auth.models import User
from marcdown.models import Note, Profile
from marcdown.serializers import NoteSerializer

class NoteViewSet(viewsets.ViewSet):
    # get
    def retrieve(self, request, pk=None):
        '''
        Gets the note corresponding to the given id,
        and responds with its description and content
        '''
        queryset = Note.objects.all()
        note = get_object_or_404(queryset, id=pk)
        serializer = NoteSerializer(note)
        return JsonResponse(serializer.data)
    
    # post (public = True, readonly = False, sharers = [])
    # needs auth
    def create(self, request):
        '''
        Creates an empty note with the given parameters
        '''
        user = request.user
        if user.is_authenticated:
            data = request.data
            note = Note(
                owner=user.profile,
                public=getattr(data, "public", True),
                read_only=getattr(data, "readOnly", False),
                title="Untitled",
                content=getattr(data, "content", ""),
            )
            note.parse_title()
            note.parse_tags()
            for sharer_name in getattr(data, "sharedWith", []):
                try:
                    sharer = User.objects.get(username=sharer_name).profile
                    note.sharers.add(sharer)
                except:
                    # TODO: error when sharer not found ?
                    pass
            note.save()
        else:
            # TODO: error ?
            pass
    
    # update (public, readonly, sharers)
    # needs auth
    def update(self, request, pk=None):
        '''
        Updates the given note with the provided parameters
        '''
        user = request.user
        if user.is_authenticated:
            data = request.data
            queryset = Note.objects.all()
            note = get_object_or_404(queryset, id=pk)

            if note.allow_update_from_user(user.profile):
                note.public = getattr(data, "public", note.public)
                note.read_only = getattr(data, "readOnly", note.read_only)
                new_sharers_names = getattr(data, "sharedWith", None)
                if new_sharers_names:
                    note.sharers.set([])
                    for sharer_name in new_sharers_names:
                        try:
                            sharer = User.objects.get(username=sharer_name).profile
                            note.sharers.add(sharer)
                        except:
                            # TODO: error when sharer not found ?
                            pass
                note.save()
            else:
                # TODO: error : not allowed
                pass
        else:
            # TODO: error : unauthenticated
            pass

    # patch (diff)
    # needs auth
    def partial_update(self, request, pk=None):
        '''
        Updates the content of the given note using the provided patch
        (generated by diff_match_patch library)
        '''
        user = request.user
        if user.is_authenticated:
            data = request.data
            queryset = Note.objects.all()
            note = get_object_or_404(queryset, id=pk)

            if note.allow_update_from_user(user.profile):
                diff = getattr(data, "diff", None)
                if diff:
                    note.update(diff)
                else:
                    # TODO: error : bad args
                    pass
            else:
                # TODO: error : not allowed
                pass
        else:
            # TODO: error : unauthenticated
            pass
    
    def destroy(self, request, pk=None):
        '''
        Deletes the given note
        '''
        user = request.user
        if user.is_authenticated:
            data = request.data
            queryset = Note.objects.all()
            note = get_object_or_404(queryset, id=pk)

            if user.profile == note.owner:
                note.delete()
            else:
                # TODO: error : not allowed
                pass
        else:
            # TODO: error : unauthenticated
            pass